spring:
  application:
    name: api-gateway-service
  
  cloud:
    gateway:
      routes:
        - id: product-info
          #uri: http://localhost:7001
          uri: lb://product-and-ratings-composite-microservice-app
          predicates:
          - Path=/info/**
          - Header=api-key, ^[a-zA-Z0-9]+$

server:
  port: 10000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    